name: Android CI

on:
  pull_request:
    branches: [ "master", "develop" ]
  push:
    branches: [ "master", "develop" ]

jobs:
  build:
    name: Build e Teste Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do Java 17 (Zulu)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache do Gradle
        uses: actions/cache@4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build com Gradle
        run: ./gradlew assembleDebug

      - name: Rodar testes unitários
        run: ./gradlew testDebugUnitTest

      - name: Upload de relatórios de teste
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/build/reports/tests/testDebugUnitTest'

      - name: Gerar relatório de cobertura Jacoco
        run: ./gradlew jacocoTestReport

      - name: Upload do relatório de cobertura (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/html
