name: Android CI

on:
  pull_request:
    branches: [ "main", "develop" ]
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build e Teste Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do Java 17 (Zulu)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache do Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build com Gradle
        run: ./gradlew assembleDebug

      - name: Rodar testes
        run: ./gradlew testDebugUnitTest

      - name: Upload de reports de teste
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/build/reports/tests/testDebugUnitTest'
